version: 0.0

os: linux
files:
  - source: /
    destination: /home/ec2-user/server
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: ec2-user
#  AfterInstall:
#    - location: scripts/change_permissions.sh
#      timeout: 300
#      runas: ec2-user
  ApplicationStart:
    - location: start_server.sh
#    - location: tmp/create_test_db.sh
      timeout: 300
      runas: ec2-user
#  ApplicationStop:
#    - location: stop_server.sh
#      timeout: 300
#      runas: ec2-user