version: 0.2

os: linux
files:
  - source: /
    destination: /tmp
hooks:
  BeforeInstall:
    - location: tmp/install_dependencies.sh
      timeout: 300
      runas: root
#  AfterInstall:
#    - location: scripts/change_permissions.sh
#      timeout: 300
#      runas: root
  ApplicationStart:
    - location: tmp/start_server.sh
#    - location: tmp/create_test_db.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: tmp/stop_server.sh
      timeout: 300
      runas: root