server:
  port: 8081

auth-service:
  uri: ${AUTH_SERVICE_URI}

main-service:
  uri: ${MAIN_SERVICE_URI}

storage-service:
  uri: ${STORAGE_SERVICE_URI}

traverse-ui:
  uri: ${TRAVERSE_UI_URI}

jwt:
  key: ${JWT_SECRET_KEY:KS8LgP4/sYt6REp8xY7HYaLbHOkyJ1PPB4PFCKjZeI8=}
spring:
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    gateway:
      enabled: true

