server:
  port: ${API_GATEWAY_PORT:8081}
  ssl:
    enabled: true
    key-alias: scg
    key-store-password: scg1234
    key-store: classpath:scg-keystore.p12
    key-store-type: PKCS12

auth-service:
  uri: ${AUTH_SERVICE_URI:http://127.0.0.1:8050}

main-service:
  uri: ${MAIN_SERVICE_URI:http://127.0.0.1:8000}

storage-service:
  uri: ${STORAGE_SERVICE_URI:http://127.0.0.1:8080}

traverse-ui:
  uri: ${TRAVERSE_UI_URI:http://127.0.0.1:3000}

jwt:
  key: ${JWT_SECRET_KEY:KS8LgP4/sYt6REp8xY7HYaLbHOkyJ1PPB4PFCKjZeI8=}
spring:
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    gateway:
      enabled: true

